
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  uptime-bot:
    build: .
    ports:
      - "8000:8000"
      
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URL=${MONGODB_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRY=${ACCESS_TOKEN_EXPIRY}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - PRODUCTION={PRODUCTION}
      - APP_URL={APP_URL}

    depends_on:
      - redis

volumes:
  redis_data:
